### ISSUE TITLE
up_nodes contains DownNodes, can't call node methods on nodes

### ISSUE THREAD

**Issue by danluu** [WesleyAC/raft#14]
If you try to get a list of up_nodes, we get DownNodes!

~~~
        leaders = collections.defaultdict(set)
        for node in self.power_broker['up_nodes'].values():
            if node.is_leader():
                leaders[node.term].add(node.node_id)
~~~

~~~
======================================================================
ERROR: runTest (hypothesis.stateful.WorldBroker.TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/danluu/dev/raft/venv/lib/python3.6/site-packages/hypothesis/stateful.py", line 191, in runTest
    run_state_machine_as_test(state_machine_class)
  File "/Users/danluu/dev/raft/venv/lib/python3.6/site-packages/hypothesis/stateful.py", line 109, in run_state_machine_as_test
    breaker.run(state_machine_factory(), print_steps=True)
  File "/Users/danluu/dev/raft/venv/lib/python3.6/site-packages/hypothesis/stateful.py", line 247, in run
    state_machine.execute_step(value)
  File "/Users/danluu/dev/raft/src/world_broker.py", line 141, in execute_step
    if node.is_leader():
AttributeError: 'DownNode' object has no attribute 'is_leader'
~~~

**Comment by danluu** [comment]
Jinny and I made the following change:

~~~
            # TODO: is up_nodes supposed to represent all nodes? If so, maybe we could call it nodes
            # If it's only nodes that are up, the commented out line below should be removed.
            # power_broker['up_nodes'][node_id] = DownNode()
~~~

I think we need to talk to Brennan about the intent of those code to understand what the actual fix should be.

**Comment by danluu** [comment]
It sounds like the fix for this is to rename 'up_nodes' to 'nodes' or 'all_nodes' and then to figure out how we should extract internal info from nodes in a consistent way.

**Comment by ghost** [comment]
I agree! That sounds like a better name
