### ISSUE TITLE
Something.... happens if we set cat level 20

### ISSUE THREAD

**Issue by danluu** [WesleyAC/raft#26]
~~~
Term #0, Node #2: Follower->Candidate
Node #2 increased term to 1
Node #2 voted for node #2
Node #3 increased term to 1
Term #0, Node #2: Follower->Candidate
Node #2 increased term to 1
Node #2 voted for node #2
Node #3 increased term to 1
Step #1: [<events.ReceiveDrop at 0x10a18a940>, <events.ReceiveDrop at 0x10a18a668>]
E
======================================================================
ERROR: runTest (hypothesis.stateful.WorldBroker.TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/danluu/dev/raft/venv/lib/python3.6/site-packages/hypothesis/stateful.py", line 191, in runTest
    run_state_machine_as_test(state_machine_class)
  File "/Users/danluu/dev/raft/venv/lib/python3.6/site-packages/hypothesis/stateful.py", line 109, in run_state_machine_as_test
    breaker.run(state_machine_factory(), print_steps=True)
  File "/Users/danluu/dev/raft/venv/lib/python3.6/site-packages/hypothesis/stateful.py", line 251, in run
    state_machine.teardown()
  File "/Users/danluu/dev/raft/src/world_broker.py", line 212, in teardown
    self.print_log()
  File "/Users/danluu/dev/raft/src/world_broker.py", line 78, in print_log
    if entry['log_type'] == 'change_type':
KeyError: 'log_type'

----------------------------------------------------------------------
Ran 1 test in 0.764s

FAILED (errors=1)
Term #0, Node #2: Follower->Candidate
Node #2 increased term to 1
Node #2 voted for node #2
Node #3 increased term to 1
~~~

One problem is that we log something that doesn't match our print log function. It's possible there's some other bad thing going on here that's masked by our code blowing up because we can't print the log.

**Comment by WesleyAC** [comment]
This seems to work now that #27 is merged.
